WIP Week 5 Problem Set
azavea/cs-fundamentals-group pull request #14
Opened 2022-07-29 17:15 UTC by rachelekm

Initial commit for [CS 50 Week 5 Problem Set](https://cs50.harvard.edu/x/2022/psets/5/speller/), spellchecker program. Due to size, `dictionaries/` and `texts/` folders have been ignored. To start program, run command:
```
./run-speller.sh [dictionary] [textfile]
```

2022-08-12 19:46 UTC, ktohalloran commented
Some visualizations of the various hash tables we've been discussing, where the [sample hash table](https://benhoyt.com/writings/hash-table-in-c/) we found online is represented at the top, the given setup within the CS50 code is in the middle, and our current method adjusted for the possibility of hash conflicts is at the bottom.
![CS50 Hash Table (1)](https://user-images.githubusercontent.com/77936689/184432048-70fdb9df-77c5-443d-9194-eeaf60bf9cbc.png)

2022-09-09 17:06 UTC, travissouthard commented
Our next if check added to the `check` function before we check the word against the dictionary will roughly look like:
```c
if (word[strlen(word)-1] == '\'')
{
            word = **NEWWORD-MINUS-LAST-LETTER**
}
```

This speficially is to allow words in the dictionary to return true, even if it comes at the end of a quote like `end` in 'This is the end'

2022-09-14 13:53 UTC, ktohalloran commented
Something to investigate on Friday&#8212;noticed this morning that this only checks up to the second to last word. For example, when run on "the cat went to the bank in the capitol to say hello to the dog" against `dictionaries/small`, it printed WORDS IN TEXT: 14 (should be 15) and identified "dog" as being spelled correctly even though it's not in the dictionary.

2022-09-16 17:22 UTC, rachelekm commented
Thanks, all! We implemented a check for words ending with apostrophes and at this point we have a functioning spellchecker 🎉 
Katie, we weren't able to replicate the spellchecker skipping the last word. Do you get the same error running with this most recent commit? Here's our output of running `./run-speller.sh dictionaries/small texts/test.txt` (that test text file is "the cat went to the bank in the capitol to say hello to the dog"):
```
MISSPELLED WORDS

the
went
to
the
bank
in
the
capitol
to
say
hello
to
the
dog

WORDS MISSPELLED:     14
WORDS IN DICTIONARY:  0
WORDS IN TEXT:        15
TIME IN load:         0.00
TIME IN check:        0.00
TIME IN size:         0.00
TIME IN unload:       0.00
TIME IN TOTAL:        0.00
```

2022-09-17 13:02 UTC, travissouthard requested changes
This is excellent. Just some cleanup notes below. And we should also rename the first commit with `git cherrypick` or some other tool (this is a good thing to pair with Terence).

2022-09-17 13:02 UTC, travissouthard commented on cs-50/week-5/dictionaries/small
> +the
I don't think we need these anymore unless you wanted to keep it around until Katie confirms the absence of that bug.

2022-09-17 13:02 UTC, travissouthard commented on cs-50/week-5/dictionary.c
> +        word[strlen(word)-1] = '\0';
We should put `word[strlen(word)-1]` into a variable called `last_letter` or something like it since we use it more than once and it's so clunky to read.

2022-09-17 13:02 UTC, travissouthard commented on cs-50/week-5/texts/test.txt
> +the cat went to the bank in the capitol to say hello to the dog''
As above, unless we're still confirming the bug, this file can go away.

2022-09-19 11:08 UTC, ktohalloran commented
Sorry for the delayed response, had a lot going on on Friday. Looks like y'all took care of the bug, thanks for finishing this one 👍

2022-09-19 11:09 UTC, ktohalloran approved these changes
👍

2022-09-19 14:54 UTC, rachelekm commented on cs-50/week-5/dictionary.c
> +        word[strlen(word)-1] = '\0';
Good call!

2022-09-19 20:07 UTC, rachelekm commented
Thanks, all! Those cleanup fixes are in and should be all set! The GH Actions CI was throwing compilation errors that I could not seem to get around and seemed like an unnecessary obstacle, so the current CI for Week 5 is echo-ing "skipping week 5" 🤷‍♀️ (Would not stop anyone if they want to try and take a whack at it!)

2022-09-20 15:07 UTC, travissouthard approved these changes
Great stuff! Thanks for finalizing the commits here!

2022-09-20 15:30 UTC, merged